backend:
  name: github
  repo: philhawksworth/sagns.com
  branch: master

media_folder: static/images/uploads
public_folder: /images

collections:
  - name: pages # Used in routes, e.g., /admin/collections/blog
    label: Pages # Used in the UI
    folder: content # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {{slug}} # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
